from enum import Enum

class MowerState(Enum):
    STOP_BUTTON_PRESSED = 1
    PARKED_BY_USER = 2
    PAUSED = 3
    MOWING = 4
    LEAVING_CHARGING_STATION = 5
    SEARCHING_FOR_CHARGING_STATION = 6
    CHARGING = 7
    ERROR = 8
    DISCONNECTED = 9